POST http://localhost:8082/api/v1/auth/login
Content-Type: application/json

{
    "email": "john@doe.com",
    "password": "12345678"
}

###
POST http://localhost:8082/api/v1/auth/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "12345678"
}

### Get Profile
GET http://localhost:8082/api/v1/auth/get-profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2M0ODcxYjQ2ODA2NjBmOGU2ZGRjNDQiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTc0MTY2NTgzOCwiZXhwIjoxNzQxNzUyMjM4fQ.pd53gSzuIpc9kX-PSnKx9xXt49_CY4PV7VMPvd-fAY0
