GET http://localhost:8080/api/v1/brands
###
GET http://localhost:8080/api/v1/brands/1
###
POST http://localhost:8080/api/v1/brands
Content-Type: application/json

{
    "name": "Electronics ",
    "description": "Electronic description"
}



###
PUT http://localhost:8080/api/v1/brands/1

Content-Type: application/json

{
    "id": 22,
    "name": "Category 22"
}
###
DELETE http://localhost:8080/api/v1/brands/2