GET http://localhost:8080/api/v1/categories
###
POST http://localhost:8080/api/v1/categories

Content-Type: application/json

{
    "id": 3,
    "name": "Category 1",
    "description": "Description 1"
}
{
    "id": 4,
    "name": "Category 1",
    "description": "Description 4"
}
###
PUT http://localhost:8080/api/v1/categories/4

Content-Type: application/json

{
    "name": "Category 12",
    "description": "Description 3"
}
