GET http://localhost:8082/api/v1/auth/login
###
GET http://localhost:8082/api/v1/categories/1

###
POST http://localhost:8082/api/v1/auth/login
Content-Type: application/json

{
    "email": "hieu532004@gmail.com",
    "password": "123456"

}


###
PUT http://localhost:8082/api/v1/categories/67c32eb49a2a181056f6e64d

Content-Type: application/json

{
    "category_name": "MINI",
    "description": "MINI description"
    
}
###
DELETE http://localhost:8082/api/v1/categories/67c32ee0894026a777b315e3
